FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY exporter.py wsgi.py ./

EXPOSE 8080

CMD ["gunicorn", "wsgi:app", "--log-level=info", "--workers", "2", "--bind", "0.0.0.0:8080"]
